### ISSUE TITLE
get geolocation data from device when picture is taken

### ISSUE THREAD

**Issue by PeterWu9** [curbmap/curbmap-ios-mvp#10]
- [ ] Change hardcode string on imageUploadText to parameters
- [ ] Location data - pending CLLocation manager

**Comment by eselkin** [comment]
To get user location, either use
* User (which is not as quickly updated as LocationServices)
    * User.currentUser.getLocation()
    * User.currentUser.getHeading()

**or**

* LocationServices (the most current location from the location manager)
    * LocationService.currentLocation.getLocation()
    * LocationServices.currentLocation.getHeading()
